name: Deploy to GitHub Pages

on:
 push:
   branches:
     - main  # Or your main branch
 workflow_dispatch:
   inputs:
     branch:
       description: 'Branch to deploy (optional, defaults to gh-pages)'
       required: false
       default: 'main'
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18  # Or your Node.js version

     - name: Install dependencies
       run: npm install

     - name: Build your app
       run: npm run build

     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
         branch: ${{ github.event.inputs.branch || 'gh-pages' }} #Use input branch or default to gh-pages